export const ROUTES: Record<string, `/${string}`> = {
  ABOUT: "/about",
  CATEGORIES: "/categories",
  CHECK: "/check",
  CLI: "/cli",
  HOME: "/",
  LLMS: "/llms.txt",
  LLMS_FULL: "/llms-full.txt",
  PEOPLE: "/people",
  PROGRAMS: "/programs",
  RSS: "/rss.xml",
  SPONSORS: "/sponsors",
  SUBMIT_PROGRAM: "/programs/submit",
  TAGS: "/tags",
};
